"""Read the schema's YAML as YAML, for the code that writes it.

Not a schema reader -- `pondie.schema.reader` is that, and it answers "what does this slot
mean" through LinkML. These are the *authoring*-side questions, and they are different in
kind: they are about the marks on the source documents rather than about the model those
documents describe. `is_marked` asks which subset an attribute was tagged with;
`own_attributes` asks what one file declares before inheritance is applied. A schema reader
has no reason to answer either, because a consumer of a record never asks them.

The generator needs raw YAML for a second reason: it *writes* YAML. `SchemaView` is a
reader with no round trip, so projecting the storage schema into the extraction schema has
to work on the documents themselves.

Everything that reads the schema to interpret a record has moved to `reader`. What was
here and is not any more -- `attributes_for`, `classify_slot`, `designated_type`,
`resolves_to`, `classify_slot`, `designated_type` -- LinkML answers, and answers better: it
applies the schema's `default_range`, which this did not.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

import yaml

#: Base class of every source-derived attribute in the extraction schema.
EXTRACTED_VALUE = "ExtractedValue"

#: The generated document-local identifier, which is never a cross-reference.
LOCAL_ID = "local_id"

#: LinkML's slot for subset membership, declared in neuroimaging-study-storage/subsets.yaml.
IN_SUBSET = "in_subset"


def own_attributes(classes: Mapping[str, object], class_name: str) -> dict[str, Mapping]:
    """Return a class's own attributes, ignoring anything it inherits."""

    definition = classes.get(class_name)
    if not isinstance(definition, Mapping):
        return {}
    attributes = definition.get("attributes") or {}
    if not isinstance(attributes, Mapping):
        return {}
    return {
        name: attribute
        for name, attribute in attributes.items()
        if isinstance(attribute, Mapping)
    }


def attribute_ranges(attribute: Mapping[str, object]) -> list[str]:
    """Every range an attribute can hold, in declaration order.

    A slot normally declares one `range`. A slot that accepts either a controlled
    value or free text declares neither, and instead lists both alternatives under
    `any_of` -- `any_of: [{range: SpatialScope}, {range: string}]`. Callers that
    reason about ranges have to see through that, or the enum branch becomes
    invisible: the MVP generator collects enums by range, so an unseen branch means
    an enum that the generated schema references but never defines.
    """

    declared = attribute.get("range")
    ranges = [declared] if isinstance(declared, str) else []
    alternatives = attribute.get("any_of")
    if isinstance(alternatives, Sequence) and not isinstance(alternatives, str):
        for alternative in alternatives:
            if isinstance(alternative, Mapping) and isinstance(alternative.get("range"), str):
                ranges.append(alternative["range"])
    return ranges


def is_marked(attribute: Mapping[str, object], subset: str) -> bool:
    """Whether an attribute declares membership in a subset."""

    declared = attribute.get(IN_SUBSET)
    if isinstance(declared, str):
        return declared == subset
    if isinstance(declared, Sequence):
        return subset in declared
    return False


def is_structural(attribute: Mapping[str, object]) -> bool:
    """Whether an attribute exists to hold the record together rather than to carry data.

    Identifiers and type designators are generated by the mapper, so no subset decision
    applies to them: a class cannot exist without them and no language model could supply
    them. Marking them anyway is harmless and some do it for the sake of an explicit
    inventory.
    """

    return attribute.get("identifier") is True or attribute.get("designates_type") is True


def is_selected(attribute: Mapping[str, object], subset: str) -> bool:
    """Whether an attribute belongs in a subset, by mark or by being structural."""

    return is_structural(attribute) or is_marked(attribute, subset)


def load_imported_classes(path: Path, key: str = "classes") -> dict[str, object]:
    """Return the merged definitions from a schema's local imports.

    `key` selects which top-level section to merge -- "classes" by default, "enums" to
    collect the vocabularies the same way.
    """

    classes: dict[str, object] = {}
    visited: set[Path] = set()

    def visit(schema_path: Path) -> None:
        schema_path = schema_path.resolve()
        if schema_path in visited:
            return
        visited.add(schema_path)

        with schema_path.open(encoding="utf-8") as stream:
            schema = yaml.safe_load(stream)
        if not isinstance(schema, Mapping):
            raise ValueError(f"{schema_path.name} must contain a YAML mapping.")

        imports = schema.get("imports", ())
        if not isinstance(imports, list):
            raise ValueError(f"{schema_path.name} imports must be a list.")
        for import_name in imports:
            if not isinstance(import_name, str) or ":" in import_name:
                continue
            import_path = schema_path.parent / import_name
            if import_path.suffix != ".yaml":
                import_path = import_path.with_suffix(".yaml")
            if not import_path.is_file():
                raise FileNotFoundError(f"Local schema import does not exist: {import_path}")
            visit(import_path)

        schema_classes = schema.get(key, {})
        if not isinstance(schema_classes, Mapping):
            raise ValueError(f"{schema_path.name} {key} must be a mapping.")
        classes.update(schema_classes)

    visit(path)
    return classes




def subclasses_of(classes: Mapping[str, object], class_name: str) -> set[str]:
    """Return every class that inherits from class_name, directly or transitively.

    A slot whose range is an abstract class holds an instance of one of its subclasses,
    so a consumer walking ranges has to follow this edge too: Analysis.details ranges on
    the abstract AnalysisDetails and never on AnalysisDetails itself.
    """

    return {
        candidate
        for candidate in classes
        if candidate != class_name and _inherits_from(classes, candidate, class_name)
    }


def _inherits_from(classes: Mapping[str, object], class_name: str, ancestor: str) -> bool:
    """Whether `class_name` is, or inherits from, `ancestor`, by the YAML's own `is_a`.

    Private, and deliberately: `Schema.resolves_to` is the public answer to this question
    and it goes through LinkML. This exists only because `subclasses_of` walks the raw
    documents for the generator, which runs before there is a model to ask.
    """
    current: str | None = class_name
    seen: set[str] = set()
    while current and current not in seen:
        if current == ancestor:
            return True
        seen.add(current)
        definition = classes.get(current)
        if not isinstance(definition, Mapping):
            return False
        parent = definition.get("is_a")
        current = parent if isinstance(parent, str) else None
    return False




